//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingVoucher
    {
        public int AccountingVoucherId { get; set; }
        public System.DateTime DocDate { get; set; }
        public System.DateTime PostingDate { get; set; }
        public string Reference { get; set; }
        public int GLAccountId { get; set; }
        public byte DebitCreditId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<short> ClassFeeId { get; set; }
        public string ShortText { get; set; }
        public short OrgId { get; set; }
        public Nullable<short> SubOrgId { get; set; }
        public byte Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<int> FeeReceiptId { get; set; }
    
        public virtual AccountingLedgerTrialBalance AccountingLedgerTrialBalance { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual StudentFeeReceipt StudentFeeReceipt { get; set; }
    }
}
