//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationRole
    {
        public short ApplicationRoleId { get; set; }
        public short ApplicationId { get; set; }
        public short RoleId { get; set; }
        public Nullable<short> PermissionId { get; set; }
        public Nullable<short> OrgId { get; set; }
        public Nullable<short> DepartmentId { get; set; }
        public Nullable<short> LocationId { get; set; }
        public byte Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public short CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
    
        public virtual MasterData MasterData { get; set; }
    }
}
