//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationDetail
    {
        public short ApplicationDetailId { get; set; }
        public Nullable<short> ApplicationId { get; set; }
        public string Logo { get; set; }
        public Nullable<byte> Active { get; set; }
    }
}
