//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationPrice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationPrice()
        {
            this.CustomerApps = new HashSet<CustomerApp>();
        }
    
        public short ApplicationPriceId { get; set; }
        public int ApplicationId { get; set; }
        public byte PCPM { get; set; }
        public byte MinCount { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string Description { get; set; }
        public short OrgId { get; set; }
        public byte Active { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual MasterData MasterData { get; set; }
        public virtual MasterData MasterData1 { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ApplicationPrice ApplicationPrice1 { get; set; }
        public virtual ApplicationPrice ApplicationPrice2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerApp> CustomerApps { get; set; }
    }
}
