//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationFeature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationFeature()
        {
            this.ApplicationFeatureRolesPerms = new HashSet<ApplicationFeatureRolesPerm>();
        }
    
        public short ApplicationFeatureId { get; set; }
        public string FeatureName { get; set; }
        public Nullable<short> ApplicationId { get; set; }
        public Nullable<byte> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationFeatureRolesPerm> ApplicationFeatureRolesPerms { get; set; }
        public virtual MasterData MasterData { get; set; }
    }
}
