//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassSubject()
        {
            this.SlotAndClassSubjects = new HashSet<SlotAndClassSubject>();
            this.StudentClassSubjects = new HashSet<StudentClassSubject>();
        }
    
        public short ClassSubjectId { get; set; }
        public short ClassId { get; set; }
        public short SubjectId { get; set; }
        public short SubjectTypeId { get; set; }
        public byte Active { get; set; }
        public short TheoryFullMark { get; set; }
        public short TheoryPassMark { get; set; }
        public Nullable<short> PracticalFullMark { get; set; }
        public Nullable<short> PracticalPassMark { get; set; }
        public Nullable<short> OrgId { get; set; }
        public Nullable<short> BatchId { get; set; }
    
        public virtual MasterData MasterData { get; set; }
        public virtual MasterData MasterData1 { get; set; }
        public virtual MasterData MasterData2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlotAndClassSubject> SlotAndClassSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClassSubject> StudentClassSubjects { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
