//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerInvoice()
        {
            this.InvoiceComponents = new HashSet<InvoiceComponent>();
            this.CustomerInvoiceItems = new HashSet<CustomerInvoiceItem>();
        }
    
        public int CustomerInvoiceId { get; set; }
        public Nullable<short> CustomerId { get; set; }
        public Nullable<int> StudentClassId { get; set; }
        public Nullable<short> DueForMonth { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime DueDate { get; set; }
        public int PaymentStatusId { get; set; }
        public short OrgId { get; set; }
        public byte Active { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual MasterData MasterData { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Organization Organization1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceComponent> InvoiceComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerInvoiceItem> CustomerInvoiceItems { get; set; }
    }
}
