//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerApp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerApp()
        {
            this.CustomerInvoiceItems = new HashSet<CustomerInvoiceItem>();
        }
    
        public short CustomerAppsId { get; set; }
        public short ApplicationPriceId { get; set; }
        public short LoginUserCount { get; set; }
        public short PersonOrItemCount { get; set; }
        public string Formula { get; set; }
        public decimal AmountPerMonth { get; set; }
        public short OrgId { get; set; }
        public byte Active { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ApplicationPrice ApplicationPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerInvoiceItem> CustomerInvoiceItems { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
