//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpEmployeeSalaryComponent
    {
        public int EmployeeSalaryComponentId { get; set; }
        public int EmployeeId { get; set; }
        public short EmpComponentId { get; set; }
        public string ActualFormulaOrAmount { get; set; }
        public decimal Amount { get; set; }
        public short OrgId { get; set; }
        public byte Month { get; set; }
        public Nullable<short> BatchId { get; set; }
        public Nullable<System.DateTime> RealeasedDate { get; set; }
        public byte Active { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EmpComponent EmpComponent { get; set; }
        public virtual EmpEmployee EmpEmployee { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
