//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpEmployeeSalaryComponent
    {
        public short EmployeeSalaryComponentId { get; set; }
        public short EmployeeId { get; set; }
        public short EmpGradeComponentId { get; set; }
        public decimal EmpployeeCompPCorAmount { get; set; }
        public decimal Amount { get; set; }
        public short OrgId { get; set; }
    
        public virtual EmpEmployee EmpEmployee { get; set; }
        public virtual EmpGradeComponent EmpGradeComponent { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
