//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpEmployee()
        {
            this.EmpEmployeeGradeSalHistories = new HashSet<EmpEmployeeGradeSalHistory>();
            this.EmpEmployeeSkills = new HashSet<EmpEmployeeSkill>();
            this.EmployeeEducationHistories = new HashSet<EmployeeEducationHistory>();
            this.EmployeeFamilies = new HashSet<EmployeeFamily>();
            this.EmployeeLeaves = new HashSet<EmployeeLeaf>();
            this.EmployeeMonthlySalaries = new HashSet<EmployeeMonthlySalary>();
            this.EmpEmployeeSalaryComponents = new HashSet<EmpEmployeeSalaryComponent>();
            this.StudTeacherClassMappings = new HashSet<StudTeacherClassMapping>();
            this.ClassSubjectTeachers = new HashSet<ClassSubjectTeacher>();
            this.AccountingLedgerTrialBalances = new HashSet<AccountingLedgerTrialBalance>();
        }
    
        public short EmpEmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public short Gender { get; set; }
        public string Address { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime DOJ { get; set; }
        public Nullable<short> CityId { get; set; }
        public string pincode { get; set; }
        public Nullable<short> StateId { get; set; }
        public Nullable<short> CountryId { get; set; }
        public string Bloodgroup { get; set; }
        public string CategoryId { get; set; }
        public string BankAccountNo { get; set; }
        public string IFSCcode { get; set; }
        public string MICRNo { get; set; }
        public string AdhaarNo { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<short> ReligionId { get; set; }
        public string ContactNo { get; set; }
        public string AlternateContactNo { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<short> ReportTo { get; set; }
        public Nullable<short> LocationId { get; set; }
        public Nullable<short> EmploymentStatusId { get; set; }
        public Nullable<short> EmploymentTypeId { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<short> NoticePeriodDays { get; set; }
        public Nullable<short> ProbationPeriodDays { get; set; }
        public string PAN { get; set; }
        public string PassportNo { get; set; }
        public Nullable<short> MaritalStatusId { get; set; }
        public Nullable<System.DateTime> MarriedDate { get; set; }
        public string PFAccountNo { get; set; }
        public short OrgId { get; set; }
        public byte Active { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<short> NatureId { get; set; }
        public Nullable<short> SubOrgId { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpEmployeeGradeSalHistory> EmpEmployeeGradeSalHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpEmployeeSkill> EmpEmployeeSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeEducationHistory> EmployeeEducationHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeFamily> EmployeeFamilies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeaf> EmployeeLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeMonthlySalary> EmployeeMonthlySalaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpEmployeeSalaryComponent> EmpEmployeeSalaryComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudTeacherClassMapping> StudTeacherClassMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassSubjectTeacher> ClassSubjectTeachers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingLedgerTrialBalance> AccountingLedgerTrialBalances { get; set; }
    }
}
