//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMonthlySalary
    {
        public short EmployeeMonthlySalaryId { get; set; }
        public System.DateTime SalaryMonth { get; set; }
        public decimal Gross { get; set; }
        public decimal Deduction { get; set; }
        public decimal NetSalary { get; set; }
        public short PresentDays { get; set; }
        public short EmployeeId { get; set; }
        public Nullable<byte> Released { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<short> OrgId { get; set; }
    
        public virtual EmpEmployee EmpEmployee { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
