//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaf
    {
        public short EmployeeLeaveId { get; set; }
        public short EmployeeId { get; set; }
        public short LeaveTypeId { get; set; }
        public System.DateTime LeaveFrom { get; set; }
        public System.DateTime LeaveTo { get; set; }
        public short NoOfLeaves { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<short> LeaveStatus { get; set; }
        public Nullable<System.DateTime> ApprovedRejectedDate { get; set; }
        public Nullable<short> ApprovedBy { get; set; }
        public string Reamarks { get; set; }
        public short OrgId { get; set; }
    
        public virtual EmpEmployee EmpEmployee { get; set; }
        public virtual MasterData MasterData { get; set; }
        public virtual MasterData MasterData1 { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
