//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeGradeLeaf
    {
        public short EmployeeGradeLeaveId { get; set; }
        public short EmployeeGradeId { get; set; }
        public short LeaveTypeId { get; set; }
        public short NoOfDays { get; set; }
        public byte Active { get; set; }
        public short OrgId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpadatedDate { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
    
        public virtual MasterData MasterData { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
