//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEducationHistory
    {
        public int EmployeeEducationHistoryId { get; set; }
        public string CourseName { get; set; }
        public short FromYear { get; set; }
        public short ToYear { get; set; }
        public short PercentageObtained { get; set; }
        public string BoardName { get; set; }
        public byte Status { get; set; }
        public int EmployeeId { get; set; }
        public short OrgId { get; set; }
    
        public virtual EmpEmployee EmpEmployee { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
