//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFamily
    {
        public short EmployeeFamilyId { get; set; }
        public short EmployeeId { get; set; }
        public short FamilyRelationShipId { get; set; }
        public short FirstName { get; set; }
        public short LastName { get; set; }
        public short Age { get; set; }
        public short Gender { get; set; }
        public short OrgId { get; set; }
    
        public virtual EmpEmployee EmpEmployee { get; set; }
        public virtual MasterData MasterData { get; set; }
        public virtual MasterData MasterData1 { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
