//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamStudentSubjectResult
    {
        public int ExamStudentSubjectResultId { get; set; }
        public short ExamId { get; set; }
        public int StudentClassSubjectId { get; set; }
        public short ClassSubjectMarkComponentId { get; set; }
        public short Marks { get; set; }
        public int ExamStatus { get; set; }
        public short OrgId { get; set; }
        public short BatchId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<byte> Active { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual ClassSubjectMarkComponent ClassSubjectMarkComponent { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual MasterData MasterData { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual StudentClassSubject StudentClassSubject { get; set; }
    }
}
