//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamStudentResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamStudentResult()
        {
            this.ExamStudentSubjectResults = new HashSet<ExamStudentSubjectResult>();
        }
    
        public short ExamStudentResultId { get; set; }
        public short ExamId { get; set; }
        public int StudentClassId { get; set; }
        public Nullable<short> TotalMarks { get; set; }
        public Nullable<short> Grade { get; set; }
        public Nullable<short> Rank { get; set; }
        public short ExamStatus { get; set; }
        public short OrgId { get; set; }
        public short BatchId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual StudentClass StudentClass { get; set; }
        public virtual MasterData MasterData { get; set; }
        public virtual MasterData MasterData1 { get; set; }
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamStudentSubjectResult> ExamStudentSubjectResults { get; set; }
    }
}
