//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamSlot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamSlot()
        {
            this.SlotAndClassSubjects = new HashSet<SlotAndClassSubject>();
        }
    
        public short ExamSlotId { get; set; }
        public short ExamId { get; set; }
        public System.DateTime ExamDate { get; set; }
        public short SlotNameId { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public byte Status { get; set; }
    
        public virtual Exam Exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlotAndClassSubject> SlotAndClassSubjects { get; set; }
    }
}
