//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamStudentSubject
    {
        public short ExamStudentSubjectId { get; set; }
        public short ExamStudentClassId { get; set; }
        public short StudentClassSubjectId { get; set; }
        public Nullable<short> Theory { get; set; }
        public Nullable<short> Practical { get; set; }
        public Nullable<short> InternalAssessment { get; set; }
        public Nullable<short> Total { get; set; }
        public Nullable<short> Status { get; set; }
    
        public virtual ExamStudentClass ExamStudentClass { get; set; }
        public virtual MasterData MasterData { get; set; }
        public virtual StudentClassSubject StudentClassSubject { get; set; }
    }
}
