//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesNPhoto
    {
        public int FileId { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public string UpdatedFileFolderName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<byte> FileOrFolder { get; set; }
        public Nullable<byte> FileOrPhoto { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> StudentClassId { get; set; }
        public Nullable<short> DocTypeId { get; set; }
        public string Parent { get; set; }
        public Nullable<short> BatchId { get; set; }
        public Nullable<short> OrgId { get; set; }
    
        public virtual MasterData MasterData { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
