//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterRolePermission
    {
        public short MasterRolePermissionId { get; set; }
        public short MasterDataId { get; set; }
        public short RoleId { get; set; }
        public short PermissionId { get; set; }
        public byte Active { get; set; }
        public short OrgId { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual MasterData MasterData { get; set; }
    }
}
