//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageHistory
    {
        public short PageHistoryId { get; set; }
        public string PageBody { get; set; }
        public string PageLeft { get; set; }
        public string PageRight { get; set; }
        public byte Version { get; set; }
        public short ParentPageId { get; set; }
        public byte Published { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Page Page { get; set; }
    }
}
