//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleUser
    {
        public short RoleUserId { get; set; }
        public short RoleId { get; set; }
        public short UserId { get; set; }
        public short OrgId { get; set; }
        public Nullable<short> DepartmentId { get; set; }
        public Nullable<short> LocationId { get; set; }
        public byte Active { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual MasterData MasterData { get; set; }
        public virtual MasterData MasterData1 { get; set; }
    }
}
