//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeeReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentFeeReceipt()
        {
            this.AccountingVouchers = new HashSet<AccountingVoucher>();
        }
    
        public int StudentFeeReceiptId { get; set; }
        public int StudentClassId { get; set; }
        public decimal TotalAmount { get; set; }
        public int ReceiptNo { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public short BatchId { get; set; }
        public short OrgId { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte Active { get; set; }
        public string OffLineReceiptNo { get; set; }
        public Nullable<decimal> Balance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingVoucher> AccountingVouchers { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
