//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAssignmentComment
    {
        public int AssignmentCommentId { get; set; }
        public int TaskAssignmentId { get; set; }
        public string Comments { get; set; }
        public short CommentedBy { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public short OrgId { get; set; }
        public byte Active { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual TaskAssignment TaskAssignment { get; set; }
    }
}
