//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskAssignment()
        {
            this.TaskAssignmentComments = new HashSet<TaskAssignmentComment>();
        }
    
        public int AssignmentId { get; set; }
        public string AssignmentName { get; set; }
        public string Description { get; set; }
        public Nullable<int> AssignedToStudentClassId { get; set; }
        public Nullable<int> AssignedToEmployeeId { get; set; }
        public int AssignedByEmployeeId { get; set; }
        public int AssignmentStatusId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<byte> Score { get; set; }
        public System.DateTime AssignmentDate { get; set; }
        public System.DateTime ExpectedCompletion { get; set; }
        public Nullable<System.DateTime> ActualCompletion { get; set; }
        public string Remarks { get; set; }
        public int BatchId { get; set; }
        public short OrgId { get; set; }
        public byte Active { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EmpEmployee EmpEmployee { get; set; }
        public virtual EmpEmployee EmpEmployee1 { get; set; }
        public virtual MasterData MasterData { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual StudentClass StudentClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAssignmentComment> TaskAssignmentComments { get; set; }
    }
}
