//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskConfiguration
    {
        public int Id { get; set; }
        public string TaskName { get; set; }
        public string DBConnection { get; set; }
        public string TableName { get; set; }
        public string ColNameNValue { get; set; }
        public Nullable<short> Action { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UserEmailForAlert { get; set; }
        public string AlertMessage { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> LastRun { get; set; }
        public Nullable<short> ApplicationId { get; set; }
    }
}
