//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableConfiguration
    {
        public string VariableName { get; set; }
        public string VariableDescription { get; set; }
        public decimal VariableAmount { get; set; }
        public string VariableFormula { get; set; }
        public byte Active { get; set; }
        public short OrgId { get; set; }
        public byte DisplayOrder { get; set; }
        public short VariableConfigurationId { get; set; }
    
        public virtual Organization Organization { get; set; }
    }
}
